baseurl = "http://beewhimzy.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "Bee Whimzy"
[params]
copyright = "&copy;2017 Bee Whimzy"
description = "Handcraft crochet clothes"
sidebarabout = ["Handcrafted in Canada ğŸ Crochet clothes for your busy ğŸ and their whimsical adventures Free shipping within ğŸ‡¨ğŸ‡¦ Email: info@beewhimzy.com"]
style = "pink"
[params.social]
email = "info@beewhimzy.com"
facebook = "https://www.facebook.com/beewhimzy/"
instagram = "https://www.instagram.com/beewhimzy/"
twitter = "https://twitter.com/beewhimzy"
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
